### ISSUE TITLE
Column width

### ISSUE THREAD

**Issue by evstratbg** [pyexcel/pyexcel-xls#22]
Hello!

How can I adjust column width?

Bogdan

**Comment by chfw** [comment]
No, with the current version you could not. However, I am planning to support column width in file writer across xls, xlsx and ods. Please watch pyexcel or this project to in order to get an update.

With that said, the underneath xlrd allows you to do control column width if you are willing to "get your hands dirty".

**Comment by evstratbg** [comment]
thank you
