### ISSUE TITLE
pyexcel-xls conflict with pyexcel-xlsx

### ISSUE THREAD

**Issue by suiyuan2009** [pyexcel/pyexcel-xls#34]
When both installed, reading https://www.edd.ca.gov/Jobs_and_Training/warn/WARN_Report.xlsx using pyexcel-xls will be stuck.

**Comment by chfw** [comment]
the solution is:

```
>>> import pyexcel as p
>>> p.get_array(file_name='WARN_Report.xlsx', library='pyexcel-xls')
```

**Comment by chfw** [comment]
the reason is: both pyexcel-xlsx and pyexcel-xls register themselves as xlsx handler. Without explicit 'library' parameter, pyexcel will choose one for you.

The best option is to install one of the two in your python application's environment.

**Comment by Themanwithoutaplan** [comment]
openpyxl doesn't hang but does take a long time to open the file. The reason is that the file contains over 42000 merged cell ranges which also have borders and openpyxl does some work to remove ambiguity from the worksheet. This is an example of a very poorly formatted worksheet that merges cells so that two completely unrelated tables appear under each other.
