### ISSUE TITLE
support xlrd==2.0.1

### ISSUE THREAD

**Issue by horpto** [pyexcel/pyexcel-xls#45]
Hello, a new version of xlrd was released last month. Do you have a plans to support it ?

**Comment by chfw** [comment]
there is not much feature change in 2.x branch: https://xlrd.readthedocs.io/en/latest/changes.html

because 2.x branch dropped xlsx read feature, I would only release another version of pyexcel-xls if xlrd will have another significant feature update.

why is it important about xlsx read? here is why: https://github.com/pyexcel/pyexcel-xls/pull/41
